# Using user_id directly in the body as I am not using sessions yet (for simplicity)
# Each request should return all events/classes/taskss for the scope (day/week/month) for the user (user_id)

### Daily view request
POST http://localhost:3000/view
Content-Type: application/json

{
  "type": "daily",
  "date": "2025-05-25",
  "user_id": "68368ed88104579d39029471"
}

###

### Weekly view request
POST http://localhost:3000/view
Content-Type: application/json

{
  "type": "weekly",
  "date": "2025-05-25",
  "user_id": "68368ed88104579d39029471"
}

###

### Monthly view request
POST http://localhost:3000/view
Content-Type: application/json

{
  "type": "monthly",
  "date": "2025-05-25",
  "user_id": "68368ed88104579d39029471"
}
